/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.admin.catalogo.application;


public abstract class UseCase<IN, OUT>  {
    
    public abstract OUT execute(IN anIn);
}
