/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.admin.catalogo.infrastructure;


public class Main {
    public static void main(String[] args) {
        System.out.println("Teste");
        // System.out.println(new UseCase().execute());
    }
}
