/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.admin.catalogo.application;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class UseCaseTest {
    
    @Test
    void testCresteUseCase() {
        // assertNotNull(new UseCase());
        // assertNotNull(new UseCase().execute());
    }
}
