/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.admin.catalogo.application;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class UseCaseTest {
    
    @Test
    void testCresteUseCase() {
        assertNotNull(new UseCase());
        assertNotNull(new UseCase().execute());
    }
}
