/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.admin.catalogo.domain;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CategoryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Category category = new Category();
        assertNotNull(category);
    }
}
